development:
  adapter: async

test:
  adapter: test

# ğŸ› ï¸ CONFIGURACIÃ“N PARA RENDER
# Usamos "async" para que los mensajes de ActionCable (Websockets)
# se manejen en la memoria del proceso.
production:
  adapter: async
  # No necesitamos URL ni channel_prefix cuando usamos async